services:
  pebble-sdk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pebble-sdk-container
    restart: unless-stopped
    volumes:
      - ./app:/workspace
    environment:
      - NVM_DIR=/home/pebble/.nvm
    ports:
      - "9000:9000" # Pebble app/timeline connection
      - "5900:5900" # VNC connection
      - "8080:80" # no-vnc web interface
    working_dir: /workspace/pebble-darkroom
    stdin_open: true
    tty: true  # Keep the container interactive
